animals/urls.py
from django.urls import path
from animals import views

app_name = 'animals'

urlpatterns = [

    path("animals_list/", views.list_animals, name = "animals_list"),
    path("create_animal", views.create_animal, name = "create_animal"),
    path("animal_details/<pk>", views.animal_details, name = "animal_details"),
    path("animal_photos/<animal_name>", views.animal_photos, name = "animal_photos"),
    path("update_animal/<pk>", views.update_animal, name = "update_animal"),
    path("delete_animal/<pk>", views.delete_animal, name = "delete_animal"),
    path("comment/<pk>", views.CommentView, name = "comment"),
    path("comments_list/<pk>", views.CommentsList, name = "comments_list"),
    path("add_photos/<pk>", views.add_photos, name = "add_photos"),

]

beats/urls.py
# Importing static and settings for the media url bellow
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url

from beats import views as v



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', v.index, name = 'index'),
    path('accounts/', include('accounts.urls', namespace = "accounts")),
    path('profiles/', include('profiles.urls', namespace = "profiles")),
    path('animals/', include('animals.urls', namespace = "animals")),
# This will allow us to load using <src> images or files when needed
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

animals/models.py
from django.contrib.auth import get_user_model
from django.db import models

UserModel = get_user_model()

# Create your models here.

class Animal(models.Model):
    animal_name = models.CharField(max_length=30, blank=True)
    is_mammal = models.BooleanField(default=False)
    animal_photo = models.ImageField(upload_to="animals", blank=True)

    def __str__(self):
        return self.animal_name


class OtherPhotos(models.Model):
    photo = models.ImageField(
        upload_to='animals/other_photos',
        blank=True
    )

    animal = models.ForeignKey(
        Animal,
        on_delete=models.CASCADE
    )

    def __str__(self):
        photo_id = self.id
        return "Photo of " + self.animal.animal_name + "with id " + str(photo_id)

# connect to user model
class Comment(models.Model):
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE)
    text = models.TextField(max_length=255, blank=True)
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)



    def __str__(self):
        return self.animal.animal_name

animals/forms.py
from animals.models import Animal, Comment, OtherPhotos

from django.forms import ModelForm
from django import forms


class AnimalForm(ModelForm):
    class Meta:
        model = Animal
        fields = ("animal_name", "is_mammal", "animal_photo")

        widgets = {
            "animal_name": forms.TextInput(attrs={'class': 'form-control'}),
            "animal_photo": forms.FileInput(attrs={'class': 'custom-file-input'}),
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)


        widgets = {
            "text": forms.Textarea(attrs={'class': 'form-control'}),
        }


class AddPhotosForm(ModelForm):
    class Meta:
        model = OtherPhotos
        fields = ("photo",)

        widgets = {
            "photo": forms.FileInput(attrs={'class': 'custom-file-input'}),
        }

animals/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from animals.models import Animal, OtherPhotos, Comment

from animals.forms import AnimalForm, CommentForm, AddPhotosForm


# Create your views here.


def list_animals(request):
    animals = Animal.objects.all()

    context = {
        "animals": animals,
    }

    return render(request, "animals/list_animals.html", context)

def create_animal(request):
    if request.method == "POST":
        form = AnimalForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect("index")

    else:
        form = AnimalForm()

    context = {
        "form": form,
    }

    return render(request, "animals/create_animals.html", context)

@login_required
def animal_details(request, pk):
    animal = Animal.objects.get(pk = pk)

    context = {"animal": animal}

    return render(request, 'animals/animal_details.html', context)


def animal_photos(request, animal_name):
    animals_photos = OtherPhotos.objects.all()
    animal = Animal.objects.get(animal_name = animal_name)


    context = {
        "animals_photos": animals_photos,
        "animal": animal
    }

    return render(request, 'animals/animals_photos.html', context)



def update_animal(request, pk):
    animal = Animal.objects.get(pk = pk)

    if request.POST:
        form = AnimalForm(request.POST, request.FILES, instance=animal)

        if form.is_valid():
            form.save()
            return redirect("animals:animals_list")
    else:
        form = AnimalForm(instance=animal)

    context = {
        "form": form,
        "animal": animal,
    }

    return render(request, "animals/update_animals.html", context)

def delete_animal(request, pk):
    animal = Animal.objects.get(pk=pk)
    animal.delete()

    return redirect("animals:animals_list")


# Make a comment for a specific animal by a specific user
def CommentView(request, pk):
    animal = Animal.objects.get(pk=pk)
    if request.POST:
        form = CommentForm(request.POST)
        if form.is_valid():
            # Comment is now the form with the posted data but still not committed to the database
            comment = form.save(commit=False)
            comment.user = request.user
            comment.animal = animal
            comment.save()
            return redirect("index")
    else:
        form = CommentForm()

    context = {"comment_form": form}

    return render(request, "animals/comment_form.html", context)


def CommentsList(request, pk):
    comments = Comment.objects.all()
    animal = Animal.objects.get(pk=pk)

    # We only want to filter the comments where the object animal of comments is equal to the
    # animal we are currently viewing in the template
    # and its compared by its primary key
    for comment in comments:
        comments = Comment.objects.filter(animal=animal)


    context = {
        "comments": comments,
        "animal": animal,
               }

    return render(request, "animals/animal_details.html", context)


# Photo is being added according to the animal
def add_photos(request,pk):
    animal = Animal.objects.get(pk=pk)
    if request.POST:
        form = AddPhotosForm(request.POST, request.FILES)

        if form.is_valid():
            photo = form.save(commit=False)
            photo.animal = animal
            photo.save()
            return redirect("index")
    else:
        form = AddPhotosForm()

    context = {
        "add_photos_form": form,
    }

    return render(request, "animals/add_photos.html", context)

animals/templates/animals/add_photos.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block add_photos %}
<br>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form add_photos_form %}
    <input type="submit" name="submit" value="submit">
</form>
{% endblock %}

animals/templates/animals/animal_details.html
<!DOCTYPE>
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}


    {% block animal_details %}
        <div class="container-fluid">
            <br>
            <div class="row">
                <div class="col-sm-3 col-md-6">
                        <p>Animal details:</p>
                        - Type:<b>{{ animal.animal_name }}</b><br>
                        - Mammal: <b>{{ animal.is_mammal }}</b><br>
                        <br>

                        <!-- Loading the photo -->
                        <img class="animal_image" alt="Animal Photo" src="{{ animal.animal_photo.url }}" />
                    <div style="margin-top: 2px;">
                    </div>
                    <br>
                        <div class="col-sm-3 col-md-6">
                        <a href="{% url 'animals:animal_photos' animal.animal_name %}"><button class="btn">Other photos</button></a>

                        <p>Update this animal?
                        <a href="{% url 'animals:update_animal' animal.id %}"><button class="btn btn-primary">Update</button></a>
                        </p>
                        <p>Or maybe delete it?
                        <a href="{% url 'animals:delete_animal' animal.id %}"><button class="btn btn-danger">Delete</button></a>
                    </p>
                        </div>

                    <p><a href="{% url 'animals:comment' animal.id %}">Write a comment?</a></p>
                    </div>

                        <div class="container comments col-sm-3 col-md-6">
                            <a href="{% url 'animals:comments_list' animal.id %}"><p>Click to check the comments:</p></a>
                            <ol>

                                {% for comment in comments %}
                                    <li><p>{{ comment.text }} - written by {{ comment.user.email }}</p></li>
                                {% endfor %}
                            </ol>
                        </div>

                        <div class="col-sm-3 col-md-6">
                            <a href="{% url 'animals:add_photos' animal.id%}"><button>Add photos</button></a>


                        </div>



                </div>
            </div>






    {% endblock %}

animals/templates/animals/animals_photos.html
<!DOCTYPE>
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}




    {% block animal_photos %}
        <div class="container-fluid">
            <div class="row">
            <div class="col-md-6">
                {% for photo in animals_photos %}
                    {% if photo.animal.animal_name == animal.animal_name %}
                        <img class="animal_image" alt="Photo" src="{{ photo.photo.url }}" />
                    {% endif %}
                {% endfor %}
            </div>
            <div class="col-md-6">

            </div>
        </div>
            </div>
    {% endblock %}

animals/templates/animals/animals_preview.html
<h2>Let's create more?</h2>
<p>Current animal number is: <b>{{ total_animals }}</b></p>

animals/templates/animals/comment_form.html
<!DOCTYPE>
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}


    {% block comment %}


     <form method="POST">
        {% csrf_token %}
        {% bootstrap_form comment_form %}

        <input type="submit" value="Comment" name="Comment" class="btn btn-primary">
    </form>


    </div>
    {% endblock %}

animals/templates/animals/comments_list.html
<!DOCTYPE>
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}


    {% block comments_list %}
        <div class="container-fluid">
            <br>
            <div class="row">
                <div class="container-fluid col-sm-3 col-md-6">
                    <p>Comments for {{ animal.animal_name }}</p>



                </div>

             <div class="container-fluid col-sm-3 col-md-6">
                    <p>Comments for {{ animal.animal_name }}</p>

                    {% for comment in comments %}
                        <p>{{ comment.text }}</p>
                    {% endfor %}

                </div>






            </div>
        </div>







    {% endblock %}

animals/templates/animals/count_mammals.html
<h4>You wonder how many are mammals?</h4>

<p><b>{{ mammals }} </b> are mammals!</p>

animals/templates/animals/create_animals.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load bootstrap4 %}

<!-- Loading count.animals.py -->
{% load count_animals %}

{% load custom_inclusion_tags %}



{% block create_animals %}


<!-- Inclusion tag -->
<br>
{% animals_preview %}

    <form method="POST" class="form" style="padding: 50px 350px 150px 350px;" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Submit" name="Submit" style="margin-top: 5px; position: relative; left: 520px;">
    </form>
    <!-- Loading count_mammals inclusion tag from custom_inclusion_tags.py -->
{% count_mammals %}



{% endblock %}

animals/templates/animals/list_animals.html
<!DOCTYPE>
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}

<!-- Loading capitalize.py from templatetags folder -->
{% load capitalize %}

{% load custom_filters %}

<!-- Loading count_animals.py from templatetags folder -->
{% load count_animals %}


{% block list_animals %}
    <p style="text-align: right;">Total animals: {% count_animals %}</p>
    <ol>
        {% for animal in animals %}

                <li style="text-align: center;
                font-size: 16px;
                 margin: 15px 15px 15px 15px;">
                    <!-- truncatechars means that it will have 10 chars -->
                   <!-- {{ animal.animal_name|lower|capfirst|truncatechars:10 }} -->
                    {{ animal.animal_name|capitalize|check_for_hey|insert_underscore_in_the_middle }} -> <a href="{% url 'animals:animal_details' pk=animal.id %}">{{ animal.animal_name|check_for_g }}</a> is mammal: <b>{{ animal.is_mammal }}</b>
                </li>

        {% endfor %}
     </ol>

    {% endblock %}

animals/templates/animals/update_animals.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load bootstrap4 %}

<!-- Loading count.animals.py -->
{% load count_animals %}

{% load custom_inclusion_tags %}



{% block update_animals %}


<!-- Inclusion tag -->
<br>
{% animals_preview %}

    <form method="POST" class="form" style="padding: 50px 350px 150px 350px;" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Update" name="Update" style="margin-top: 5px; position: relative; left: 520px;">
    </form>

{% count_mammals %}



{% endblock %}