accounts/urls.py
from django.urls import path

from django.conf.urls import url

from accounts import views

app_name = "accounts"

urlpatterns = [

	path("register/", views.register, name = "register"),
	path("login", views.sign_in, name = "login"),
	path("logout", views.sign_out, name = "logout"),

	

]

animals/urls.py
from django.urls import path
from animals import views

app_name = 'animals'

urlpatterns = [

    path("animals_list/", views.list_animals, name = "animals_list"),
    path("create_animal", views.create_animal, name = "create_animal"),
    path("animal_details/<pk>", views.animal_details, name = "animal_details"),
    path("animal_photos/<animal_name>", views.animal_photos, name = "animal_photos"),
    path("update_animal/<pk>", views.update_animal, name = "update_animal"),
    path("delete_animal/<pk>", views.delete_animal, name = "delete_animal"),
    path("comment/<pk>", views.CommentView, name = "comment"),
    path("comments_list/<pk>", views.CommentsList, name = "comments_list"),
    path("add_photos/<pk>", views.add_photos, name = "add_photos"),

]

beats/urls.py
# Importing static and settings for the media url bellow
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url

from beats import views as v



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', v.index, name = 'index'),
    path('accounts/', include('accounts.urls', namespace = "accounts")),
    path('profiles/', include('profiles.urls', namespace = "profiles")),
    path('animals/', include('animals.urls', namespace = "animals")),
# This will allow us to load using <src> images or files when needed
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path

from profiles import views



app_name = "profiles"

urlpatterns = [

    path("profile_details/", views.profile_details, name = "profile_details"),


]

import profiles.signals

templates/_navbar.html
<nav id = "navbar" class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand active" href="{% url 'index' %}">SoftUni</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if not user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
        </li>
        {% else %}
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'animals:animals_list' %}">Animals</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'animals:create_animal' %}">Create Animal</a>
        </li>
        {% endif %}

        {% if user.is_superuser %}
        <li class="nav-item">
          <a href="{% url 'admin:index' %}">Admin Panel</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
       <!-- <button class="btn btn-outline-success" type="submit">Search</button> -->
      </form>
    </div>
  </div>
</nav>

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
{% load profile_complete_notification %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

	<link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">

	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" integrity="undefined" crossorigin="anonymous">

	<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

	<script type="text/javascript" src="{% static 'accounts/js/style.js' %}"></script>

	<title></title>

	<style>
	body {
	  margin: 0;
	  font-size: 14px;
	  font-family: Arial, Helvetica, sans-serif;
	}

	#navbar {
	  overflow: hidden;
	  background-color: dodgerblue;
	}


	/* User .content + .sticky, basically our navbar does not overslap the page content (the body of the HTML page) */

	.content {
	  padding: 16px;
	}

	.sticky {
	  position: fixed;
	  top: 0;
	  width: 100%;
	}

	.sticky + .content {
	  padding-top: 60px;
	}
</style>

	
</head>
<body>

	{% include '_navbar.html' %}

	<!-- Text-muted makes text grey -->
	<div class="container text-muted content">
		{% block index %}
		{% endblock %}

		<!-- Templatetag to check if profile is completed -->
		{% if request.user.is_authenticated %}
			{% profile_complete_notification %}
		{% endif %}

        {% block create_animal %}
        {% endblock %}

	

		{% block register %}

		{% endblock %}

		{% block profile_details %}

		{% endblock %}

        {% block create_animals %}

        {% endblock %}

        {% block update_animals %}
        {% endblock %}

        {% block list_animals %}
        {% endblock %}

        {% block animal_details %}
        {% endblock %}

        {% block animal_photos %}
        {% endblock %}

        {% block comment %}
        {%  endblock %}

        {% block comments_list %}
        {% endblock %}

        {% block add_photos %}
        {% endblock %}
	</div>



  <!-- Copyright -->
  <footer class="footer">
	  <div class="text-center p-3 text-white">
	    	<p class="text-white">Stiliyan Goshev - SoftUni Project</p>
	  </div>
  <!-- Copyright -->
</footer>

<script>
	window.onscroll = function() {myFunction()};

	var navbar = document.getElementById("navbar");
	var sticky = navbar.offsetTop;

	function myFunction() {
	  if (window.pageYOffset >= sticky) {
	    navbar.classList.add("sticky")
	  } else {
	    navbar.classList.remove("sticky");
	  }
	}
</script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}


{% block index %}

<p><h3>Hello <a href="{% url 'profiles:profile_details' %}">{{ request.user }}</a></h3></p>


{% endblock %}